apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: nilecare
  labels:
    app: gateway-service
    tier: gateway
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: gateway
        image: nilecare/gateway-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_NAME
          value: "gateway-service"
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: AUTH_SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              name: gateway-secrets
              key: AUTH_SERVICE_API_KEY
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:7020"
        - name: CLINICAL_SERVICE_URL
          value: "http://clinical-service:7001"
        - name: BUSINESS_SERVICE_URL
          value: "http://business-service:7010"
        - name: DATA_SERVICE_URL
          value: "http://data-service:7003"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:7002"
        - name: BILLING_SERVICE_URL
          value: "http://billing-service:7011"
        - name: CORS_ORIGIN
          value: "https://app.nilecare.com,https://admin.nilecare.com"
        - name: RATE_LIMIT_WINDOW_MS
          value: "900000"
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/startup
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: nilecare
  labels:
    app: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: nilecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15

