apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: nilecare
  labels:
    app: billing-service
    tier: business
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
        tier: business
    spec:
      containers:
      - name: billing-service
        image: nilecare/billing-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: PORT
          value: "5003"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: JWT_SECRET
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: ALLOWED_ORIGINS
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: KAFKA_BROKERS
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: NOTIFICATION_SERVICE_URL
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: STRIPE_SECRET_KEY
        - name: PAYPAL_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: PAYPAL_CLIENT_ID
        - name: PAYPAL_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: PAYPAL_CLIENT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: nilecare-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: nilecare
  labels:
    app: billing-service
    tier: business
spec:
  selector:
    app: billing-service
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: billing-service-hpa
  namespace: nilecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: billing-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
