apiVersion: v1
kind: ConfigMap
metadata:
  name: nilecare-config
  namespace: nilecare
data:
  # Database configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "nilecare"
  DB_USER: "nilecare"
  DB_PASSWORD: "nilecare123"
  
  # MongoDB configuration
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DB: "nilecare"
  MONGO_USER: "nilecare"
  MONGO_PASSWORD: "nilecare123"
  
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  
  # Kafka configuration
  KAFKA_BROKER: "kafka-service:9092"
  
  # JWT configuration
  JWT_SECRET: "nilecare-jwt-secret-key-2024"
  JWT_EXPIRES_IN: "24h"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:3001"
  GATEWAY_SERVICE_URL: "http://gateway-service:3000"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3002"
  
  # Clinical Domain Services
  EHR_SERVICE_URL: "http://ehr-service:4001"
  CDS_SERVICE_URL: "http://cds-service:4002"
  MEDICATION_SERVICE_URL: "http://medication-service:4003"
  LAB_SERVICE_URL: "http://lab-service:4004"

  # Business Domain Services Configuration
  FACILITY_SERVICE_URL: "http://facility-service:5001"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5002"
  BILLING_SERVICE_URL: "http://billing-service:5003"
  INVENTORY_SERVICE_URL: "http://inventory-service:5004"

  # Integration & Interoperability Services Configuration
  FHIR_SERVICE_URL: "http://fhir-service:6001"
  HL7_SERVICE_URL: "http://hl7-service:6002"
  DEVICE_INTEGRATION_SERVICE_URL: "http://device-integration-service:6003"
  
  # Business & Data Services
  BUSINESS_SERVICE_URL: "http://business-service:3005"
  DATA_SERVICE_URL: "http://data-service:3006"
  
  # External services
  KEYCLOAK_URL: "http://keycloak-service:8080"
  MQTT_BROKER_URL: "mqtt://mqtt-broker:1883"
  
  # Monitoring
  PROMETHEUS_URL: "http://prometheus-service:9090"
  GRAFANA_URL: "http://grafana-service:3000"
  JAEGER_URL: "http://jaeger-service:16686"
  
  # Environment
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # CORS
  CLIENT_URL: "http://localhost:3000"
  
  # File upload limits
  MAX_FILE_SIZE: "10mb"
  
  # Rate limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: nilecare
data:
  kong.yml: |
    _format_version: "3.0"
    
    services:
      # Gateway Service (Main API Gateway)
      - name: gateway-service
        url: http://gateway-service:3000
        routes:
          - name: gateway-routes
            paths:
              - /api/v1
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 1000
                  hour: 10000
              - name: jwt
              - name: prometheus
      
      # Auth Service
      - name: auth-service
        url: http://auth-service:3001
        routes:
          - name: auth-routes
            paths:
              - /api/v1/auth
              - /auth/oauth2
              - /auth/oidc
            methods:
              - GET
              - POST
              - PUT
              - PATCH
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 20
                  hour: 200
              - name: prometheus
      
      # Notification Service
      - name: notification-service
        url: http://notification-service:3002
        routes:
          - name: notification-routes
            paths:
              - /api/v1/notifications
              - /ws/notifications
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 100
                  hour: 1000
              - name: jwt
              - name: prometheus
      
      # EHR Service
      - name: ehr-service
        url: http://ehr-service:4001
        routes:
          - name: ehr-routes
            paths:
              - /api/v1/ehr
              - /api/v1/problem-lists
              - /api/v1/soap-notes
              - /api/v1/progress-notes
              - /api/v1/clinical-documents
              - /api/v1/medical-history
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 100
                  hour: 1000
              - name: jwt
              - name: prometheus
      
      # Clinical Decision Support Service
      - name: cds-service
        url: http://cds-service:4002
        routes:
          - name: cds-routes
            paths:
              - /api/v1/drug-interactions
              - /api/v1/allergy-alerts
              - /api/v1/dose-validation
              - /api/v1/clinical-guidelines
              - /api/v1/contraindications
              - /api/v1/alerts
              - /api/v1/check-medication
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 200
                  hour: 2000
              - name: jwt
              - name: prometheus
      
      # Medication Service
      - name: medication-service
        url: http://medication-service:4003
        routes:
          - name: medication-routes
            paths:
              - /api/v1/mar
              - /api/v1/barcode-verification
              - /api/v1/reconciliation
              - /api/v1/high-alert-monitoring
              - /api/v1/medications
              - /api/v1/administration
              - /api/v1/medication-administration
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 150
                  hour: 1500
              - name: jwt
              - name: prometheus
      
      # Lab Service
      - name: lab-service
        url: http://lab-service:4004
        routes:
          - name: lab-routes
            paths:
              - /api/v1/lab-orders
              - /api/v1/result-processing
              - /api/v1/critical-values
              - /api/v1/quality-control
              - /api/v1/specimens
              - /api/v1/instruments
              - /api/v1/process-lab-result
              - /api/v1/hl7
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 100
                  hour: 1000
              - name: jwt
              - name: prometheus

      # Business Domain Services
      # Facility Service
      - name: facility-service
        url: http://facility-service:5001
        routes:
          - name: facility-routes
            paths:
              - /api/v1/facilities
              - /api/v1/departments
              - /api/v1/wards
              - /api/v1/beds
              - /api/v1/settings
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 100
                  hour: 1000
              - name: jwt
              - name: prometheus

      # Appointment Service
      - name: appointment-service
        url: http://appointment-service:5002
        routes:
          - name: appointment-routes
            paths:
              - /api/v1/appointments
              - /api/v1/schedules
              - /api/v1/resources
              - /api/v1/waitlist
              - /api/v1/reminders
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 200
                  hour: 2000
              - name: jwt
              - name: prometheus

      # Billing Service
      - name: billing-service
        url: http://billing-service:5003
        routes:
          - name: billing-routes
            paths:
              - /api/v1/billing
              - /api/v1/claims
              - /api/v1/payments
              - /api/v1/insurance
              - /api/v1/reporting
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 100
                  hour: 1000
              - name: jwt
              - name: prometheus

      # Inventory Service
      - name: inventory-service
        url: http://inventory-service:5004
        routes:
          - name: inventory-routes
            paths:
              - /api/v1/inventory
              - /api/v1/items
              - /api/v1/suppliers
              - /api/v1/orders
              - /api/v1/locations
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 100
                  hour: 1000
              - name: jwt
              - name: prometheus

      # Integration & Interoperability Services
      # FHIR Service
      - name: fhir-service
        url: http://fhir-service:6001
        routes:
          - name: fhir-routes
            paths:
              - /fhir
              - /fhir/Patient
              - /fhir/Observation
              - /fhir/Condition
              - /fhir/MedicationRequest
              - /fhir/Encounter
              - /fhir/metadata
              - /fhir/$export
              - /oauth2
              - /.well-known/smart-configuration
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 300
                  hour: 3000
              - name: jwt
              - name: prometheus

      # HL7 v2.x Service
      - name: hl7-service
        url: http://hl7-service:6002
        routes:
          - name: hl7-routes
            paths:
              - /api/v1/hl7/adt
              - /api/v1/hl7/orm
              - /api/v1/hl7/oru
              - /api/v1/hl7/messages
              - /api/v1/hl7/mllp
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 200
                  hour: 2000
              - name: jwt
              - name: prometheus

      # Device Integration Service
      - name: device-integration-service
        url: http://device-integration-service:6003
        routes:
          - name: device-routes
            paths:
              - /api/v1/devices
              - /api/v1/vital-signs
              - /api/v1/monitors
              - /api/v1/alerts
              - /api/v1/calibration
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 500
                  hour: 5000
              - name: jwt
              - name: prometheus
      
      # Business Service
      - name: business-service
        url: http://business-service:3005
        routes:
          - name: business-routes
            paths:
              - /api/v1/appointments
              - /api/v1/billing
              - /api/v1/scheduling
              - /api/v1/staff
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            strip_path: false
            plugins:
              - name: cors
              - name: rate-limiting
                config:
                  minute: 100
                  hour: 1000
              - name: jwt
              - name: prometheus
    
    plugins:
      - name: prometheus
      - name: cors
      - name: rate-limiting
