apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehr-service
  namespace: nilecare
  labels:
    app: ehr-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ehr-service
  template:
    metadata:
      labels:
        app: ehr-service
        version: v1
    spec:
      containers:
      - name: ehr-service
        image: nilecare/ehr-service:latest
        ports:
        - containerPort: 4001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: NODE_ENV
        - name: PORT
          value: "4001"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: LOG_LEVEL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: jwt-secret
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: REDIS_PORT
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: KAFKA_BROKER
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/startup
            port: 3005
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ehr-service
  namespace: nilecare
  labels:
    app: ehr-service
spec:
  selector:
    app: ehr-service
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ehr-service-hpa
  namespace: nilecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ehr-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
