apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-service
  namespace: nilecare
  labels:
    app: fhir-service
    tier: integration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fhir-service
  template:
    metadata:
      labels:
        app: fhir-service
        tier: integration
    spec:
      containers:
      - name: fhir-service
        image: nilecare/fhir-service:latest
        ports:
        - containerPort: 6001
        env:
        - name: PORT
          value: "6001"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: DATABASE_URL
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: MONGODB_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: JWT_SECRET
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: ALLOWED_ORIGINS
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: KAFKA_BROKERS
        - name: EHR_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: EHR_SERVICE_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 6001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 6001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: nilecare-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fhir-service
  namespace: nilecare
  labels:
    app: fhir-service
    tier: integration
spec:
  selector:
    app: fhir-service
  ports:
  - port: 6001
    targetPort: 6001
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fhir-service-hpa
  namespace: nilecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fhir-service
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
