apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: nilecare
  labels:
    app: gateway-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
        version: v1
    spec:
      containers:
      - name: gateway-service
        image: nilecare/gateway-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: LOG_LEVEL
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: AUTH_SERVICE_URL
        - name: CLINICAL_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: CLINICAL_SERVICE_URL
        - name: BUSINESS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: BUSINESS_SERVICE_URL
        - name: DATA_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: DATA_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: NOTIFICATION_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: jwt-secret
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: REDIS_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/startup
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: nilecare
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-service-hpa
  namespace: nilecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-service
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
