apiVersion: apps/v1
kind: Deployment
metadata:
  name: hl7-service
  namespace: nilecare
  labels:
    app: hl7-service
    tier: integration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hl7-service
  template:
    metadata:
      labels:
        app: hl7-service
        tier: integration
    spec:
      containers:
      - name: hl7-service
        image: nilecare/hl7-service:latest
        ports:
        - containerPort: 6002
          name: http
        - containerPort: 2575
          name: mllp
        env:
        - name: PORT
          value: "6002"
        - name: MLLP_PORT
          value: "2575"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nilecare-secrets
              key: JWT_SECRET
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: ALLOWED_ORIGINS
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: KAFKA_BROKERS
        - name: EHR_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: EHR_SERVICE_URL
        - name: FHIR_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: nilecare-config
              key: FHIR_SERVICE_URL
        resources:
          requests:
            memory: "384Mi"
            cpu: "500m"
          limits:
            memory: "768Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 6002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 6002
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: nilecare-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hl7-service
  namespace: nilecare
  labels:
    app: hl7-service
    tier: integration
spec:
  selector:
    app: hl7-service
  ports:
  - port: 6002
    targetPort: 6002
    protocol: TCP
    name: http
  - port: 2575
    targetPort: 2575
    protocol: TCP
    name: mllp
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hl7-mllp-service
  namespace: nilecare
  labels:
    app: hl7-service
    tier: integration
spec:
  selector:
    app: hl7-service
  ports:
  - port: 2575
    targetPort: 2575
    protocol: TCP
    name: mllp
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hl7-service-hpa
  namespace: nilecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hl7-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
