apiVersion: v1
kind: Namespace
metadata:
  name: nilecare
  labels:
    name: nilecare
    app: healthcare-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nilecare-quota
  namespace: nilecare
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nilecare-limits
  namespace: nilecare
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
